### ISSUE TITLE
Can't create new knife items

### ISSUE THREAD

**Issue by Datan** [QinomeD/kubejsdelight#11]
Using 1.19.2 Forge 43.3.5, kubejsdelight 1.1, kubejs 6.2 build 50.
Registering a new knife item causes a crash. Registering new pies works fine. The script I'm using:
```
// priority: 0

ItemEvents.toolTierRegistry(event => {
	event.add('steel', tier => {
		tier.level = 2
		tier.uses = 1000
		tier.speed = 7.0
		tier.attackDamageBonus = 3.0
		tier.enchantmentValue = 11
		tier.repairIngredient = '#forge:ingots/steel'
	})
  })
  
StartupEvents.registry('item', event => {
	event.create('lead_plate').displayName('Lead Plate')
	event.create('steel_rod').displayName('Steel Rod')
	event.create('steel_wire').displayName('Steel Wire')
	event.create('steel_knife', 'farmers_delight:knife').displayName('Steel Knife').tier('steel')
})
```

The startup log:
[startup.log](https://github.com/QinomeD/kubejsdelight/files/14073742/startup.log)

**Comment by QinomeD** [comment]
It's farmersdelight, not farmers_delight

**Comment by Datan** [comment]
Yeah that fixed it, thank you. Can't believe I missed that when I have other references to farmersdelight. Maybe update the mod description? That's whatI based the knife script on.
![Capture](https://github.com/QinomeD/kubejsdelight/assets/10764349/ad730c5f-690c-4c21-a1b5-e6e7567c8028)

**Comment by QinomeD** [comment]
yeah maybe I'll delete the examples in the mod description and just leave the wiki
