### ISSUE TITLE
When trying to create feasts greater than 4, minecraft crashes

### ISSUE THREAD

**Issue by HavenError** [QinomeD/kubejsdelight#14]
I tried to create servings greater than 4 and my minecraft just crashed.

StartupEvents.registry("block", event => {
  event.create('example_feast', 'farmersdelight:feast')
    .servingsAmount(5)
    .servingItems(['minecraft:bread', 'minecraft:apple', 'minecraft:carrot', 'minecraft:golden_apple', 'minecraft:golden_carrot'])
    .displayName('Example Feast')
})

I originally wanted to implement my “rice rolls” block, but first I decided to test the functionality of “.servingsAmount (n)” and finally when I put more than 4, my minecraft crashed.

(Sorry for my bad English, I wrote this post with the help of a translator)

The crash report:
[crash-2024-07-30_15.25.27-client.txt](https://github.com/user-attachments/files/16426211/crash-2024-07-30_15.25.27-client.txt)

**Comment by QinomeD** [comment]
Fixed in 1.1.2!
