### ISSUE TITLE
Couldn't create cutting recipe with multiple ingredient

### ISSUE THREAD

**Issue by EvanHsieh0415** [QinomeD/kubejsdelight#5]
code is from [wiki.latvian.dev/kubejs-farmers-delight](https://wiki.latvian.dev/books/kubejs/page/kubejs-farmers-delight)
```js
ServerEvents.recipes((event) => {
    event.recipes.farmersdelight.cutting(
        "minecraft:cobblestone",
        "#forge:tools/pickaxes", // tool
        [ // results
            "minecraft:iron_ore",
            {
                item: "minecraft:diamond",
                chance: 0.8
            }
        ],
        "" // sound
    );
});
```
```diff
! [18:31:14] [ERR] server_scripts:script.js:2: Failed to create recipe for type 'farmersdelight:cutting': Custom recipe has to use a single json object argument!
```

**Comment by QinomeD** [comment]
what's your KubeJS Delight version?

**Comment by BobVarioa** [comment]
hmmm could you post your modlist? and anything else in your server scripts? 
i can't reproduce this issue in my environment

**Comment by BobVarioa** [comment]
So I've been playing around with this issue, and I have no clue why this is happening, but I think my current verdict is just to update to kubejs 6.1 when it comes out later today or this week, because it doesn't happen in that version.
