### ISSUE TITLE
Upload releases to curseforge/modrinth/github releases

### ISSUE THREAD

**Issue by FlynnLies** [QinomeD/kubejsdelight#6]
Hi would be nice to have recipes in the public releases without having to compile yourself. 
Please upload both one for KubeJS 6.0 and 6.1 for added support with other mods. (Or make it compatible with with both)

**Comment by BobVarioa** [comment]
KubeJSDelight has a curseforge page? 6.1 hasn't released yet so there isn't a version publicly available yet
